name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          # Los siguientes se ejecutan en la instancia EC2
          script: |
            cd ~
            # Se clona el repo si no existe, de otro modo, se hace un pull
            if [ ! -d "my-app" ]; then
              git clone "https://github.com/${{ github.repository }}" my-app
            else
              cd my-app
              git pull
            fi

            sudo apt update
            sudo apt install --upgrade nodejs npm -y
            cd ~/my-app
            npm install
            npm run build || true
            npm run kill
            npm start &
